### ISSUE TITLE
AWS KMS Key for Vanta

### ISSUE THREAD

**Issue by bprice169** [quintevents/sales-agent-api#7]
This apparently is preventing Vanta from getting updated asset owners.  One of the ISO requirements is having a complete inventory with assigned asset owners.

[alias/aws/acm](https://console.aws.amazon.com/kms/home?region=us-east-1#/kms/keys/19f8a3b9-a9cb-41d7-813e-93c8662f78eb): Got an error with ListTagsOfResourceCommand: AccessDeniedException: User: arn:aws:sts::287584413379:assumed-role/vanta-auditor/Vanta-1724253400431 is not authorized to perform: kms:ListResourceTags on resource: arn:aws:kms:us-east-1:287584413379:key/19f8a3b9-a9cb-41d7-813e-93c8662f78eb because no resource-based policy allows the kms:ListResourceTags action

**Comment by rishka** [comment]
This should be solved. That role has access to that action now:

![Image](https://github.com/user-attachments/assets/60e82b85-5b91-4682-b915-890ec2b85100)
